from dotenv import load_dotenv
import os

load_dotenv()

AZURE_SEARCH_ENDPOINT = os.getenv("AZURE_SEARCH_ENDPOINT")
AZURE_SEARCH_ADMIN_KEY = os.getenv("AZURE_SEARCH_API_ADMIN_KEY")
AZURE_SEARCH_API_QUERY_KEY = os.getenv("AZURE_SEARCH_API_QUERY_KEY")
AZURE_OCR_ENDPOINT = os.getenv("AZURE_OCR_ENDPOINT")
AZURE_OCR_API_KEY = os.getenv("AZURE_OCR_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING")

# --- OCR Confidence Thresholds & Multipliers ---
HIGH_VALUE_MULTIPLIER = 2.0
STANDARD_MULTIPLIER = 1.0
STOP_WORD_MULTIPLIER = 0.0
IMPORTANT_WORD_LOW_CONF_THRESHOLD = 70.0

